client/app/models/Bam.iobio.js, client/app/models/Vcf.iobio.js, package-lock.json, package.json
Added local file support for bam and vcf files using Anders' fi-bridge proxy
=> Local file proxy

client/app/components/pages/GeneHome.vue, client/app/components/partials/TranscriptsMenu.vue, client/app/components/viz/GeneVariantsCard.vue, client/app/components/viz/VariantAllCard.vue, client/app/components/viz/VariantInspectCard.vue, client/app/globals/GlobalApp.js, client/app/models/GeneModel.js, client/app/models/GenomeBuildHelper.js
Removed references to old backend, showing transcript on gene entered, only show left panel if files were entered.  Only load gene-viz after left panel is entered on file upload, styling dbSnp url for consistency, fixed coverage tooltip position
=> Styling and bug fixes

client/app/models/CohortModel.js, package-lock.json
This PR shows "non significant" and "poor quality" variants as reviewed.
=> Show non-sig and poor-qual variants in review

client/app/components/pages/GeneHome.vue, client/app/globals/GlobalApp.js
Backend fix to only point to new backend, centralized server population in Global App.  Checked network and console logs to make sure that genomebuild, geneinfo, and geneToPheno servers all point to the correct backend.
=> Backend fix

client/app/components/viz/VariantInspectCard.vue, client/app/d3/PedigreeGenotypeChart.d3.js
dbSnp Url vertical alignment fix, zygosity badge vertical alignment fix, fixed pedigree line connectivity issue, show allele bar for unknown sex, positioned affected glyph closer to node for unknown sex, added back in commas to alt, ref counts, positioned affected glyph closer to female node, fixed female het-hom positioning inconsistency
=> Pedigree styling

client/app/components/partials/FilterSettings.vue, client/app/components/viz/FlaggedVariantsCard.vue
Hi @tonydisera 
This is a fix to issue in clin.iobio repo, the top of filter modal is hidden: https://github.com/iobio/clin.iobio/issues/136
It adds a scroll only when launched from clin to avoid clipping of the modal inside the iframe.
=> New filter modal appears behind title bar

client/app/components/viz/DepthViz.vue, client/app/components/viz/GeneViz.vue, client/app/components/viz/VariantAllCard.vue, client/app/d3/Line.d3.js
Exon tooltip shows correct coverage on otherTracks when depth-viz-coverage-glyphs are hovered over
=> Coverage bug

client/app/components/partials/FilterSettings.vue, client/app/components/viz/FlaggedVariantsCard.vue
Removed ability to add custom filters, made existing filters uneditable
=> Disable filters

client/app/components/pages/GeneHome.vue
This issue was caused by isNewAnalysis() returning false incorrectly in gene. I closed the issue in Clin and opened up a new issue in Gene
=> Reviewed variants in clin

package-lock.json, package.json
@mvelinder  Updated vue-pileup to use newest version of igv.js
=> updated vue-pileup to newest version of igv.js

client/app/components/partials/TranscriptsMenu.vue, client/app/components/viz/GeneVariantsCard.vue, client/app/components/viz/GeneViz.vue, client/app/d3/Gene.d3.js
Fixed non-canonical transcript showing by default, fixed canonical label not showing up in transcript menu, found and fixed bug where canonical tag disappears in transcript menu after a gene is deselected then reselected.  Transcript no longer showing up when a gene is entered with no files uploaded, as my solution to this caused the bug with the canonical label not showing in the transcript menu. I will submit an issue and figure out the proper way to display the transcript when a gene is entered but no files are uploaded first thing tomorrow.
=> Canonical transcript fix2

client/app/components/pages/GeneHome.vue
This allows clin.iobio to launch with a gene set from Utah Mosaic.  Issue # 401
=> Feature gene sets in clin

client/app/models/CohortModel.js
Added bam and vcf index files to demo data
=> Demo index files

client/app/components/pages/GeneHome.vue
fixed igv modal positioning inside Clin
=> Igv clin position

client/app/components/pages/GeneHome.vue, client/app/components/partials/TranscriptsMenu.vue, client/app/components/viz/GeneVariantsCard.vue, client/app/components/viz/GeneViz.vue
Added transcript to gene-variants-card when no files are loaded, made sure to not introduce same bug last time I tried to do this
=> Transcript no files

client/app/components/pages/GeneHome.vue, client/app/components/partials/GenesPanel.vue
Fixed wide margin and styled gene panel 'Analyze all', 'stop analysis', and 'Call variants' buttons
=> Margin and button styling

client/app/components/pages/GeneHome.vue
(After launching a saved gene.iobio analysis, the app wasn't auto-saving when variants were interpreted or notes were added.)
=> Fix auto-save bug.  #440. 

client/app/components/pages/GeneHome.vue, client/app/components/viz/GeneVariantsCard.vue
Show snackbar warning message when user enters a gene with no files uploaded
=> No data notice

client/app/components/viz/GeneVariantsCard.vue, client/app/components/viz/GeneViz.vue, client/app/components/viz/VariantAllCard.vue, client/app/d3/Gene.d3.js
Update gene-viz exon coverage warning glyph on coverage threshold change.  Fixed bug where gene-viz was displaying warning glyph values for proband on otherTracks
=> Gene viz exon coverage

client/app/components/viz/Navigation.vue
Positioned terms of service closer to menu dropdown button
=> moved terms of service button closer to menu dropdown button

client/app/components/viz/Navigation.vue
Changed terms of service wording as per Al's request
=> changed wording on terms of service

client/app/components/viz/FlaggedVariantsCard.vue
Sorting reviewed variants in gene left side variant pannel by significance.  This PR corresponds to the following issue on the clin.iobio project board: 
https://github.com/iobio/clin.iobio/issues/141
=> Sort variants by sig

client/app/components/pages/GeneHome.vue, client/app/components/viz/FlaggedVariantsCard.vue, client/app/components/viz/VariantAllCard.vue, client/app/models/CohortModel.js
Assigning significance to user flagged variants now properly displays in the left gene panel in both gene standalone and gene when launched from clin.  This fixes both a bug in gene not described in the issues, and issue: https://github.com/iobio/clin.iobio/issues/145 in clin.
Bug discovered not introduced by this code:  
Issue: Selecting a variant that appears in the left panel with the variant-viz, and assign a significance.  The significance is not updated in the left panel 
Solution: When a variant is selected through the left panel, the corresponding varint in the variant-viz is selected.  To fix this bug, when a flagged variant is selected in the variant-viz, select the corresponding variant in the left panel.
I will open a separate issue to fix this discovered bug
=> Add selected variants

client/app/components/partials/FilterSettings.vue, client/app/components/viz/FlaggedVariantsCard.vue, client/app/models/FeatureMatrixModel.js, client/app/models/FilterModel.js
Issues addressed in this PR:
1) Custom filter title not displaying: https://github.com/iobio/gene.iobio.vue/issues/384
2) Cannot delete custom filter: https://github.com/iobio/gene.iobio.vue/issues/385
3) Creating a new filter removes assigned significance inside clin: https://github.com/iobio/gene.iobio.vue/issues/390
4) All attributes can be removed from a filter and applied: https://github.com/iobio/gene.iobio.vue/issues/386
5) New filter doesn't generate variants: https://github.com/iobio/gene.iobio.vue/issues/387
6) Filter popout cut off by bottom of page when launched from clin: https://github.com/iobio/gene.iobio.vue/issues/493
=> Filter bug fixes

client/app/components/partials/GeneAssociationsDialog.vue, client/app/components/viz/VariantInspectCard.vue
@WilliamRichards2017 this fixes the same issue that you had noticed in clin.iobio PR:https://github.com/iobio/clin.iobio/pull/204
=> Fix styling issues in gene association column

client/app/components/pages/GeneHome.vue
Flagged Variants with annotations are now saved in analysis
=> saving analysis when user flagged variant selected

client/app/components/partials/VariantInspectInheritanceRow.vue, client/app/components/partials/VariantInspectRow.vue
Glyph padding fix for variant-inspect-row unremarkable glyphs.
=> Padding fix

client/app/components/pages/GeneHome.vue, client/app/components/viz/Navigation.vue, client/app/components/viz/Welcome.vue
Changed terms of service glyph, added file upload icon to navigation toolbar, added upload data button on welcome page
=> Obvious file input

client/app/components/pages/GeneHome.vue, client/app/components/partials/SaveButton.vue, client/app/components/viz/Navigation.vue
Moved mosaic save button to top.
Snackbar appears in center of screen when saving.
=> Fixed issue #470

client/app/components/pages/GeneHome.vue, client/app/components/partials/VariantInspectInheritanceRow.vue, client/app/components/viz/VariantInspectCard.vue, client/app/globals/GlobalApp.js
Inheritance and conservation visualization hotfix branched directly from gene_4.1
=> Gene 4.1.1

client/app/components/pages/GeneHome.vue, client/app/models/HubSession.js, client/app/models/HubSessionDeprecated.js, client/app/routes.js
refactoring mosaic api endpoint from apiv1/ to api/v1/
Removing endpoint for client-application, grabbing client-application-id from url params
=> Internal endpoints

client/app/components/viz/Navigation.vue
Remove legend from clin until we decide how and where we want to display legend in when launched from clin
=> removing legend from clin till we figure out how we want to display it

client/app/models/GeneModel.js
Pointing phenolyzer server to use new back end
=> replacing nv-prod phenolyzer with new backend

client/app/components/pages/GeneHome.vue, client/app/models/CohortModel.js
This PR address fixes for gene when launched from clin using custom data.  There were a couple of issues of variants not being added to the analysis payload when using custom data, and this fix makes sure that variants are added to the clin payload whenever the gene list is updated.  Specifically, this PR adresses addresses https://github.com/iobio/clin.iobio/issues/225 and https://github.com/iobio/clin.iobio/issues/194
=> Flagged variants for clin

client/app/components/pages/GeneHome.vue, client/app/models/CohortModel.js
This fixes clin hanging when there is a gene in the geneList with no variants.  The issue was caused by the gene not being added to the intersectedGenes list, so the gene is added with a null variant
=> adding empty variant to intersectedGenes if gene contains no variants

client/app/components/viz/VariantViz.vue
Updating variant viz when region is updated by zoom brush
=> fixed zooming for variant viz

client/app/components/pages/GeneHome.vue, client/app/components/viz/Navigation.vue
This PR fixes and will show the same variants count in gene.iobio right sidebar and in clin workflow nav badge. 
Issue: #551 
To test: 
- Use the branch https://github.com/iobio/clin.iobio/tree/integrate-variant-sets in clin 
- Test with Demo data set or by launching from Mosaic. 
- variants count should be same in gene.iobio right sidebar and in clin workflow nav badge.
=> Clin variants count badge

client/app/components/pages/GeneHome.vue
This PR should send interpreted variants to clin.
=> fix: send interpreted variants to clin

client/app/models/GeneModel.js
=> getting ncbi info for specified gene in getLinks

client/app/models/GeneModel.js
Adding pubMed link to external links dropdown
=> Pub med link

client/app/components/viz/VariantInspectCard.vue
changing gnomAD variant inspect header, replacing freq with frequency
=> changed gnomAd freq wording

client/app/components/pages/GeneHome.vue
Dynamically resizing up/downstream region to accommodate for larger regions
=> dynamically updating region bugger width

client/app/components/viz/GeneVariantsCard.vue
Reverting to fixed region 'bugger' size. Limiting buffer to 99,999 base pairs to prevent gene from crashing when Matt enters 100 billion BP region
=> changing region buffer to fixed size, limiting region buffer to 99,999

client/app/components/pages/GeneHome.vue, client/app/components/partials/FilesDialog.vue, client/app/models/Bam.iobio.js, client/app/models/EndpointCmd.js, client/app/models/HubSession.js, client/app/models/SampleModel.js, client/app/models/VariantExporter.js, client/app/models/Vcf.iobio.js, package.json
Catching and displaying errors caught from iobio backend, and mosaic backend.  For each error, report my interpretation of the problem, action items, help contact information, and the console/ service error.  Also removed references to the old backend in EndpointCmd.js
=> Error handling

client/app/components/partials/VariantToggle.vue, client/app/components/viz/VariantAllCard.vue, client/app/components/viz/VariantViz.vue, client/app/models/FilterModel.js
Inheritance filter now only filters based on inheritance, and not from the default left panel filters.  Code is much cleaner now
=> Inheritance filter fix

client/app/components/partials/AppIcon.vue, client/assets/sass/_variables.sass
Changing zygosity badge to display correct text, darkening het background color slightly for text readability.
=> Zygosity badge

client/app/components/partials/FilesDialog.vue
Fixing issue with user uploaded vcfs not being error checked properly, fixing user upload error checking to allow only a vcf.
=> User upload fix

client/app/components/pages/GeneHome.vue, client/app/components/viz/Navigation.vue, client/app/components/viz/Welcome.vue
Adding a link to  gene.iobio title  back to homepage with navigation guard
=> adding navigation back to homepage with warning navigation gaurds

client/app/components/partials/ExportVariants.vue, client/app/models/CohortModel.js, client/app/models/VariantExporter.js
Fixing issues with exporting and importing variants.  Single click to save and download export file, fixed issue with variants getting bypassed when exporting as vcf, fixed issue where only last flagged variant got saved to vcf, fixed issue where genes weren't loaded on variant import, added description to what is getting exported in export dialog
=> Variant export

client/app/components/pages/GeneHome.vue
first flagged variant will only be selected if user is on that gene, otherwise, the user will stay on the gene, and the variants tab will be selected to show the analyzed variants.  needs to be tested from clin and saved analysis
=> Not changing users focus to first flagged variant if user selects a gene

client/app/components/pages/GeneHome.vue, client/app/models/CacheHelper.js
Changing coverage thresholds reanalyzes coverage for all genes, while keeping a consistent selected gene and variant state
=> Analyze gene coverage

client/app/components/viz/FlaggedVariantsCard.vue, client/app/components/viz/Navigation.vue
This PR should allow for the variant card in the left panel to always be highlighted if it corresponds to the selected variant under all circumstances
=> working selected variant retention in left variants panel

client/app/components/pages/GeneHome.vue, client/app/components/viz/DepthViz.vue, client/app/components/viz/FlaggedVariantsCard.vue
Rescale the coverage depth axis on zoom
=> Depth rescale

client/app/models/VariantExporter.js
This PR is to import variants with VCF file in clin.iobio. It fixes and adds missing fields while exporting variants in VCF format
=> Gene name -Annotation for vcf export

client/app/components/pages/GeneHome.vue, client/app/components/partials/GenesPanel.vue
Removing the analyze coverage PR that introduced bugs into clin
https://github.com/iobio/clin.iobio/issues/279#issuecomment-716599352
https://github.com/iobio/clin.iobio/issues/304
=> Anayze coverage ripout

client/app/components/pages/GeneHome.vue
Clin.iobio issue: https://github.com/iobio/clin.iobio/issues/307
=> focus needs to be placed on a gene

client/app/components/pages/GeneHome.vue, client/app/components/partials/FilesDialog.vue, client/app/components/viz/Navigation.vue
This PR fixes the issue https://github.com/iobio/gene.iobio.vue/issues/653 and #609 
To test: 
Launch gene.iobio from quarantest. 
(You will get a warning: Unable to access OMIM, click OK)
Select Load your data
Select trio and GRcH38
Use the following URL's
https://iobio.s3.amazonaws.com/samples/bam/NA12878.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/bam/NA12891.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/bam/NA12892.GRCh38.bam
https://iobio.s3.amazonaws.com/samples/vcf/platinum-exome.GRCh38.vcf.gz
Add gene F5
Check if all tracks are visible 
Refresh the link, so gene.iobio is now launched with URL. Check if all tracks are available. 
Also the hyperlink on the title gene.iobio should be removed.
=> Parents track not available

client/app/components/partials/AppIcon.vue
Oops.  This should have been on its own branch for testing.  (Should have been a branch named 665_inheritance_glyphs)
=> #665 Change recessive R glyph to AR and change X glyph to XL

client/app/components/pages/GeneHome.vue, client/app/components/partials/GenesPanel.vue, client/app/components/viz/FlaggedVariantsCard.vue, client/app/components/viz/Navigation.vue
=> # 754 Tony analyze all on variants tab

client/app/components/pages/GeneHome.vue
Use new Mosaic api for variant sets.
=> April 27, 2022 Meeting https://github.com/iobio/calypso/issues/45

client/app/globals/GlobalApp.js, package.json
=> Upgrade iobio-api-client to 0.10.0 for new server logging.

client/app/components/viz/Welcome.vue
Fixed the typo on the welcome page
=> Typo fixed#962

client/app/components/partials/SampleData.vue
Added an inform user text to ask the user to select a sample before loading
=> Added inform user text#943

client/app/components/partials/TranscriptsMenu.vue
=> Reorder transcripts #976

client/app/components/pages/GeneHome.vue, client/app/components/partials/SelectVariantAnnotationsDialog.vue, client/app/components/viz/VariantInspectCard.vue
Fixed the mosaic annotations not updated when changing to another selectedVariant.
Fixed the selectAll button to select mosaic annotaitons.
=> Fixed the mosaic annots not updated#1036
