.env.template
.gitignore
README.md
client/app/App.vue
package-lock.json
package.json
webpack.config.js

- The webpack test config may need to be updated as well to prevent errors.
- I've added an example in `App.vue`.  Make sure to delete this.

Adds dotenv-webpack plugin to support a .env file

---

build.sh
deploy.sh
quarantest.json
quarantest_build.sh

@tonydisera I'm done with the MVP for my service for automatically creating demo versions of our apps for each pull requests (and actually each push). The service is called quarantest. This PR adds the necessary plumbing for gene to interact with the service. The biggest change is factoring out some of the deploy script into a separate build.sh script, which can be re-used by quarantest.
I've already added the necessary webhook. Once this is merged, the quarantest bot will automatically create links like this for each push, and post them on the appropriate PRs:
[http://9c821f4cbe9316133983b43c4918441b5da8a226.quarantest.iobio.io/](http://9c821f4cbe9316133983b43c4918441b5da8a226.quarantest.iobio.io/)

Add quarantest

---

client/app/components/pages/GeneHome.vue

This Pull request should fix the following issue in clin.iobio repo: https://github.com/iobio/clin.iobio/issues/131
Testing steps: 
Use the branch fix-gene-association 
**Standalone mode**: 
1. Launch clin.iobio (localhost:4030) and load with demo data. 
2. Go to step 2 (select phenotypes) and submit the example note.
3. Select the condition (ex. Dejerine sotas disease) and phenotypes (ex. charcot marie tooth disease and dejerine sotas disease) and generate the gene list 
4. Go to step 3 (Review variants). Variant PRX should show Gene Associations (See screenshot). The current version of clin.iobio is not showing any gene associations.  
5. Mark the variant as significant
6. Go to step 4 (Report findings). Gene association should be shown for gene PRX. 
**Launch from Mosiac** 
Select MPPH …

fix-associated genes not showing in clin.iobio

---

.github/workflows/deployStage.yml

This pull request will set up auto-deployment on `dev` branch. 
Successful merge or push to `dev` will deploy it automatically to https://stage.clin.iobio.io/
Workflow: 
- Install dependencies 
- Build project 
- Upload content to S3 bucket (stage/gene.iobio.ioo)
- Invalidate CloudFront distribution 
Any point of failure in the above workflow will fail the process and stop the deployment to stage.gene.iobio.io
This script has been tested on dev.gene and the current version (2018-11-06 18:57 PT) of http://dev.gene.iobio.io/ was deployed with it 
@tonydisera @mvelinder

Set stage auto deployment

---

client/app/components/partials/OptionalTracksMenu.vue

removing sfari from optional tracks as the SFARI data is not available to the public.  We will likely need a way to figure out how to display this track only to authorized users in the future.  This PR is associated with issue 155 in the Clin board.

removing SFARI from optional tracks 

---

client/app/components/pages/GeneHome.vue

Fixes issue #449.  Make sure that 'Review Variants' refreshes correctly when chaning from 'Enter Phenotypes' to 'Review Variants'.

Fixes issue #449 

---

client/app/components/pages/GeneHome.vue

Issue #374: In clin.iobio, reviewed variants left pannel is auto refreshed to display significance when variant significance is selected.
Issue #376: When a note is added to a variant, and no significance is selected, significance defaults to unknown-significance (Depends on fix for #374 to work properly with left panel refreshing to show updated significance)

Notes no sig

---

client/app/components/pages/GeneHome.vue
client/app/models/GenomeBuildHelper.js
client/data/genomebuild.json

Since we weren't using the /genomebuild endpoint in a queried
manner, we can inline it to avoid a request, and simplify the
backend.
* genomebuild JSON file statically imported using webpack
* GenomeBuildHelper no longer needs to return a promise. Options
now passed directly to constructor.

Inline genomebuild

---

client/app/components/pages/GeneHome.vue

Removed call to refresh gene badges when coverage threshold is updated

removed unused refreshGeneBadge when coverage is updated

---

client/app/components/pages/GeneHome.vue
client/app/components/viz/VariantInspectCard.vue
client/app/models/SampleModel.js

Display genomAD pop frequencies for clinVar variants.  It seems like most clinVar variants have a gnomAd pop frequency of 0 or null, so you may have to check multiple genes before finding a clinVar variant with a gnomAd frequency above 0.  I have included screenshots of a couple of clinVar variants with non-null gnomAD frequencies for verification.  If it is unexpected that we would be seeing this many clinVar variants with null or 0 AF in gnomAD,  let me know and I can further investigate if this correctly displays gnomAD AF for all clinVar variants!

Clin var freq

---

client/app/components/pages/GeneHome.vue

**This issue was caused when a variant was assigned a significance, then deselected and reselected.  This PR fixes this issue, and allows for the proper opening, closing, and conditional rendering of the review variant panel.**
Bugs/undesirable behavior discovered but not introduced by this PR: 
1) When a variant selected in the left panel, and the transcript is changed, the variant needs to be reselected in the left panel for the Variant-All-Card to be rendered.
2) When a variant is selected,  and the transcript is changed, then the variant is deselected and reselected, the canonical transcript is gotten for the variant, and the change in the transcript was not saved.  This is inconsistent with the transcript behavior when a gene is selected, the transcript is changed, then the gene is …

Close review

---

client/app/components/viz/DepthViz.vue
client/app/components/viz/GeneViz.vue
client/app/components/viz/VariantViz.vue

This PR fixes the unnecessary rendering of the depth-viz, gene-viz, and variant-viz components.  Before, when these tracks were loading, they would be rerendered when new genes were analyzed.  Whenever a new track is selected, all tracks would be reloaded.  Now, the gene-viz and variant-viz tracks are only re-rendered when there is a meaningful change in the data.  There is still a flicker of the depth-viz on load and when a new track is selected.  When this re-rendering occurs, there is an actual change in the data being passed into the depth-viz, so I could not check to see if the data changed to prevent this re-rendering.   This does, however, prevent the re-rendering of the depth-viz with null data.

Track rendering

---

client/app/components/pages/GeneHome.vue
client/app/components/viz/Navigation.vue

When a user enters a phenotype and replaces the gene list, the variant-detail-card is updated to display the newly selected variant (or to not display if there are no variants in the replaced gene list)

update variant-detail-card on user entered phenotype

---

client/app/components/partials/FilterSettings.vue

described issue from Al - "Ok. If I create a new filter and just set ClinVar significance to pathogenic then create the filter; the filter is created, but the clinvar significance requirement disappears, so basically all variants get dropped into the filter. If I edit the filter, I see that nothing is applied, so set pathogenic again, but it doesn't get applied"

fixed clivar significance not being saved when filter applied

---

client/app/components/pages/GeneHome.vue
client/app/components/partials/VariantInspectInheritanceRow.vue
client/app/components/viz/VariantInspectCard.vue

Inheritance and conservations visualizations now properly render when gene is launched from standalone.  Inheritance labels now properly displayed when gene is launched from mosaic or from standalone.  Inheritance labels for gene when launched from clin needs to be fixed with a separate PR for clin.iobio.

Inheritance conservation hotfix

---

client/app/components/pages/GeneHome.vue
client/app/components/viz/VariantViz.vue
client/app/d3/Gene.d3.js

Recalculate gene-viz orientation when the region is updated with zoom.  For orientation center calculation, filter out all regions not contained within the zoom region.  If no regions are visible, orientation is in the middle of the region.  If only 1 region is visible, orientation is in the center of the largest empty region.

recalculating strand orientaiton position based on region zoom

---

client/app/components/pages/GeneHome.vue

Addressing issue mentioned in slack when trying to access a property of null when launched from clin

adding check to prevent null value error when launched from clin

---

client/app/components/partials/InfoPopup.vue
client/app/components/partials/VariantToggle.vue
client/app/components/viz/VariantAllCard.vue

Implemented code review changes suggested in slack yesterday.  Renamed VariantFilter to variant-toggle, fixed HTML indentation, refactored variant toggle info button to use InfoPopup component.  Did not refactor inline styling to CSS yet, as this caused unexpected inheritance issue

4.2 style cleanup

---

client/app/components/pages/GeneHome.vue
client/app/components/partials/OptionalTracksMenu.vue
client/app/components/viz/VariantViz.vue
client/app/models/CohortModel.js

Prevents the re-rendering of variant tracks when optianalTracks menu is close, check if data changed in a meaningful way when updating variant-viz

Clin var reload fix

---

client/app/components/pages/GeneHome.vue

This PR avoids making extra request calls to annotate variants when launched from clin.
To test:
- Use the branch `integrate-variants-set` https://github.com/iobio/clin.iobio/tree/integrate-variant-sets for clin.iobio 
- Launch a project from Mosaic with variant sets in clin (Do the URL trick to change URL localhost:4030). 
- Go to `review-variants`
- All the genes should be analyzed and variants should be imported.

Variants sets integration in clin 

---

client/app/globals/GlobalApp.js

Changing the clinvar URLs to point to the iobio backend when launched from Mosaic.  This branch was branched directly from gene_4.3.2, which I believe is what production is currently pointing to.

point cinvar to iobio backend when launched from mosaic

---

client/app/components/partials/VariantInspectInheritanceRow.vue
client/app/components/viz/GeneVariantsCard.vue
client/app/components/viz/VariantInspectCard.vue
client/app/d3/PedigreeGenotypeChart.d3.js
client/app/models/GeneModel.js

Emergency fixes for 4.3.6
1) alt/ref pedigree clipping on triple-digit counts
2) NCBI broken link
3) PubMed link
4) up/downstream clipping and limit region buffer BP to 99,999
5) gnomAd title and pop/freq replaced with full words
6) Removed text and glyph from pedigree inheritance title for any n/a inheritance

Will gene 4.3.6

---

client/app/components/viz/VariantInspectCard.vue
client/app/d3/PedigreeGenotypeChart.d3.js

Reducing font size - positioning bottom row text conditional on digit length to ensure that 3 digit worst case scenario (888 alt, 888 ref) isn't cut off.
To test: go to project 111 and launch gene with the 'Filtered Candidates' variant set.  Click on a bunch of different variants and make sure that the pedigree ref/alt count text looks nice on all cases (1 digit, 2 digit, 3 digit, mixed digits)

Pedigree overlap

---

client/app/globals/GlobalApp.js

Keeping logic in place to detect if launched from mosaic for when we want to switch over to use Mosaic clinvar links.  Using iobio backend clinVar links in public gene for consistency, and tested stability. 
("If geneinfo and genomebuild are still pointed at backend.iobio.io, it might be best to keep the ClinVar stuff pointed there for consistency. Eventually we should get everything pointed into the PE though I think" - Anders)

changing public gene clinVar url to point to iobio backend

---

client/app/components/partials/FilesDialog.vue

On user upload, disable sibling selection if vcf only contains 1 sample id, and have error message explaining why sibling selection is disabled, sibling selection styling improvements.

Sibling entry

---

client/app/components/pages/GeneHome.vue
client/app/components/viz/VariantViz.vue
client/app/d3/Variant.d3.js

Consistent selected variant state across zooming. Variants should not be deselected when the gene-viz is zoomed, and variants can now be selected when the track is zoomed in.

Zoom selected variant

---

client/app/components/partials/GeneBadge.vue
client/app/components/partials/GenesPanel.vue
client/app/components/viz/FlaggedVariantsCard.vue
client/app/components/viz/VariantInspectCard.vue
client/app/models/GeneModel.js

Similar to last PR (https://github.com/iobio/gene.iobio.vue/pull/629). Source indicator visuals have changed. 
Clin branch: https://github.com/iobio/clin.iobio/tree/feature-review-top-n-genes
Issue: https://github.com/iobio/gene.iobio.vue/issues/625
Do npm install as its dependency packages have been updated.
To test it> Run clin with demo data > Add phenotypes > Top 20 genes will be selected by default. > Go to review variants > Genes selected from phenotype step should be passed on > Also the source should be indicated in the genes and variant tab on left sidebar and also in the variant inspect card.

Review n genes

---

client/app/components/viz/VariantAllCard.vue

Added loading glyphs to clinVar and other variant tracks.  The COL101 issue was an issue inside the backend involving missing clinVar fields, but Steph looked into this and came up with a solution.  The changes to the backend should be deployed and available for testing by the end of the day.

Other tracks loading indication

---

client/app/components/pages/GeneHome.vue

The issue with the incorrect text being displayed when gene is launched without a phenotype search bar has already been fixed (Nebula was not up to date with newer versions of gene). 
Al mentioned to break up the 'Enter a gene name or phenotype term' into two separate dialogs.  Currently, snack bars are not set up in a way to easily display multiple snack bars at the same time in a centered container.  I have instead increased the duration that the message is available, and made it closeable. 
At this point in time, I believe the dialog message to be sufficiently clear for all modes of gene.iobio, and suggest we move the request to break up the message into two separate messages, and better align the Nebula specific message into a lower priority issue.  Is this approach okay with …

increasing duration of Enter gene message, making window close-able

---

.idea/gene.iobio.vue.iml
client/app/components/pages/GeneHome.vue
client/app/components/viz/VariantAllCard.vue

This PR addresses the inconsistency in focus changing on analyzeAll completed.  Clin and gene should now have the same behavior.  If a user clicks a gene before the analysis is completed, they will not lose focus of the gene card on analysis complete, but the gene tab will switch to the variant tab.  If a user does not select a gene, their focus will be changed to the first flagged variant and the corresponding gene

Click detection

---

client/app/components/pages/GeneHome.vue

This PR fixes the following in clin.iobio: Notes were not added to the findings page after significance was attached. For example: Add a note to a variant > Unknown significance is added > Variants also shows up on the "report-findings" page with the note that was added. > Now add another note to the same variant > New note is added in the "review variants" but does not show up in the "report findings". 
To test: 
- Pull the latest version of clin from the `dev` branch. 
- Launch clin.iobio with the demo data 
- Go to review variants 
- Add a note to a variant
- This variant should be shown on the report-findings page with unknown significance. 
- Add another note to the same variant. report-findings page should show this note. 
- Select another variant 
- Add a significance to it …

clin - variants notes report findings fix

---

client/app/components/partials/TranscriptsMenu.vue
client/app/components/viz/GeneViz.vue

Passed the "selectedTranscript" to the viz so that we can conditionally render the classes based on if there is a selected transcript or not if not select MANE.
It seems that 'transcriptSelected' is emitted up the tree `transcriptsMenu->transcriptCart->geneHome` where it is used to then update the state of other components. Something about this causes the geneViz to re-render and call that 'transcriptClass' function that we looked at.
Passing the selectedTranscript an additional level down to the geneViz & adding some conditional logic in that function that uses the selectedTranscript if it is present seems to get this working like we would expect.

Pass selectedTranscript to Viz #983
